
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude: 
    - build/** 
    - lib/components/loader_internal.dart
    - lib/core/manager/constants.dart
    - lib/**.g.dart
    - lib/**.freezed.dart
  errors:
    todo: ignore
    missing_return: error
    dead_code: info
    library_private_types_in_public_api: ignore
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:

  rules:
    avoid_print: false  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: false  # Uncomment to enable the `prefer_single_quotes` rule
    await_only_futures: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_relative_imports: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    valid_regexps: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: false
    always_specify_types: false
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_as: false
    avoid_classes_with_only_static_members: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_returning_null: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    camel_case_extensions: true
    camel_case_types: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    deprecated_consistency: true
    directives_ordering: true
    do_not_use_environment: true
    empty_catches: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: true
    implementation_imports: true
    library_names: true
    library_prefixes: true
    library_private_types_in_public_api: false
    lines_longer_than_80_chars: true
    missing_whitespace_between_adjacent_strings: true
    no_default_cases: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    no_runtimeType_toString: true
    noop_primitive_operations: true
    omit_local_variable_types: true
    overridden_fields: true
    package_api_docs: true
    prefer_asserts_in_initializer_lists: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_contains: true
    prefer_function_declarations_over_variables: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_inlined_adds: true
    prefer_is_empty: true
    prefer_int_literals: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    provide_deprecation_message: true
    recursive_getters: true
    sized_box_for_whitespace: true
    Size_box_shrink_expand: true
    slash_for_doc_comments: true
    sort_constructors_first: false
    sort_unnamed_constructors_first: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_final: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: false
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_named_constants: true
    use_raw_strings: true
    sort_pub_dependencies: true

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 5
    maximum-nesting-level: 4
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-unnecessary-setstate
    - avoid-returning-widgets
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file
    # - prefer-moving-to-variable
    - prefer-async-await
    - avoid-use-expanded-as-spacer
    - avoid-wrapping-in-padding
    - prefer-match-file-name:
        exclude:
          - lib/**_store.dart
    - prefer-immediate-return
    - prefer-first
    - prefer-last
    - no-object-declaration
    - ban-name
    - avoid-unused-parameters
    - avoid-unnecessary-type-casts
    - avoid-unnecessary-type-assertions
    - avoid-unrelated-type-assertions
    - avoid-throw-in-catch-block
    - avoid-non-null-assertion
    # - avoid-ignoring-return-values
    - avoid-global-state
    - avoid-duplicate-exports
    - avoid-collection-methods-with-unrelated-types
  anti-patterns:
    - long-method
    - long-parameter-list

